fold_id: 1
img_size: 224
max_epochs: 100
model_arch: regnety_640.seer
lr: 1e-6
scheduler: lambda
seed: 42
train_bs: 64
val_bs: 256
num_workers: 16
ft_mode: full
metric: 'val_f1_weighted'

dataset_path: "../data/"
transform_path: "configs/transforms/alpha_transforms.py"
