fold_id: 1
img_size: 224
lr: 0.0005
max_epochs: 100
seed: 42
train_bs: 64
val_bs: 64
num_workers: 8
checkpoint_filename: "serene-sweep-4_epoch89_val_mAP_weighted0.87.ckpt"
transform_path: "configs/transforms/alpha_transforms.py"