fold_id: 1
img_size: 224
lr: 0.03
max_epochs: 100
seed: 42
train_bs: 64
val_bs: 64
train_frac: 0.1
val_frac: 0.25
num_workers: 0
dataset_path: "data/"
dataset_csv_path: "dataset"

verbose: true
wandb_project: "CV2024"
entity: "wuesuv"
