fold_id: 1
img_size: 224
eta_min: 0.005
max_epochs: 10
model_arch: regnety_640.seer
seed: 42
train_bs: 32
val_bs: 64
num_workers: 8
dataset_path: "data/"
dataset_csv_path: "dataset"
wandb_project: "CV2024"
entity: "wuesuv"