program: train.py
project: "CV2024"
method: grid
metric:
  goal: maximize
  name: val_AUC_macro
parameters:
  # === Model ===
  model_arch:
    values: [ 'regnety_640.seer' ]

  # === Training ===
  max_epochs:
    values: [ 25 ]
  seed:
    values: [ 42 ]
  train_bs:
    values: [ 64 ]
  val_bs:
    values: [ 64 ]
  img_size:
    values: [ 224, 128, 96, 64, 32 ]

  # === Optimizer ===
  optimizer:
    values: [ 'adabelief' ]
  lr:
    values: [ 0.03, 0.01]

  # === Scheduler ===
  scheduler:
    values: [ 'cosine' ]
  eta_min:
    values: [ 0.005 ]

command:
  - ${env}
  - python
  - ${program}
