# Hyperparameters that are project specific can be stored in the project.yaml file.
wandb_project: "CV2024"
entity: "wuesuv"

checkpoint_dir: "checkpoints"

pretrained_checkpoint_dir: '../master-thesis/checkpoints'

dataset_path: "../data/"
dataset_csv_path: "../endoscopy/datasets/cvip2024"

transform_path: 'configs/transforms/alpha_transforms.py'
