fold_id: 1
img_size: 224
lr: 1e-6
max_epochs: 10
seed: 42
train_bs: 16
val_bs: 64
num_workers: 16
ft_mode: full

checkpoint_filename: "run-20240826_194035-ancient-forest-381/best_epoch92_val_f1_weighted0.84.ckpt"
