# === Model ===
model_arch: eva02_base_patch14_224.mim_in22k
model_type: seer

# === Paths ===
pretrained_checkpoint_dir: pretrained_models
checkpoint_filename: winter-sweep-29_epoch47_val_f1_weighted0.92.ckpt
transform_path: "configs/transforms/alpha_transforms.py"

# === Training ===
max_epochs: 50
seed: 42
train_bs: 16
val_bs: 16
fold_id: 1
img_size: 224
num_workers: 8
ft_mode: full

# === Optimizer ===
lr: 1e-6
optimizer: adabelief
metric: 'val_AUC_macro'

# === Scheduler ===
scheduler: lambda
lambda_factor: 0.95
