program: train.py
entity: "wuesuv"
project: "CV2024"
method: grid
metric:
  goal: maximize
  name: val_recall_macro
parameters:
  # === Model ===
  model_arch:
    values: [ 'eva02_base_patch14_224.mim_in22k' ]
  model_type:
    values: [ 'timm' ]

  checkpoint_filename:
    values: [ run-20241017_190933-fancy-shape-452/best_epoch32_val_recall_macro0.81.ckpt' ]

  # === Training ===
  max_epochs:
    values: [ 50 ]
  seed:
    values: [ 42 ]
  train_bs:
    values: [ 16, 64 ]
  val_bs:
    values: [ 128 ]
  fold_id:
    values: [ 0 ]
  img_size:
    values: [ 224 ]
  num_workers:
    values: [ 8 ]
  ft_mode:
    values: [ 'full' ]

  # === Optimizer ===
  optimizer:
    values: [ 'adabelief' ]
  lr:
    values: [ 1e-6 ]
  metric:
    values: [ 'val_recall_macro' ]

  # === Scheduler ===
  scheduler:
    values: [ 'lambda' ]
  lambda_factor:
    values: [ 0.95 ]

command:
  - ${env}
  - python
  - ${program}
