program: train.py
entity: "wuesuv"
project: "CV2024"
method: grid
metric:
  goal: maximize
  name: val_AUC_macro
parameters:
  # === Model ===
  model_arch:
    values: [ 'eva02_base_patch14_224.mim_in22k' ]
  model_type:
    values: [ 'seer' ]

  pretrained_checkpoint_dir:
    values: [ '../master-thesis/checkpoints' ]
  checkpoint_filename:
    values: [ 'sweep-p8wbgkdu/winter-sweep-29_epoch47_val_f1_weighted0.92.ckpt' ]

  # === Training ===
  max_epochs:
    values: [ 50 ]
  seed:
    values: [ 2, 11, 42 ]
  train_bs:
    values: [ 16, 64 ]
  val_bs:
    values: [ 64 ]
  fold_id:
    values: [ 1 ]
  img_size:
    values: [ 224 ]
  num_workers:
    values: [ 8 ]
  ft_mode:
    values: [ 'full' ]

  # === Optimizer ===
  optimizer:
    values: [ 'adabelief' ]
  lr:
    values: [ 1e-6 ]
  metric:
    values: [ 'val_AUC_macro' ]

  # === Scheduler ===
  scheduler:
    values: [ 'lambda' ]
  lambda_factor:
    values: [ 0.95 ]

command:
  - ${env}
  - python
  - ${program}
